---
# Documentation: https://github.com/SUNET/bootstrap-docker-builds
git:
  branch: main
triggers:
  github_push: true
clean_workspace: true
pre_build_script:
- cp docker/Dockerfile .
script:
- echo "Build SUNET Custom ARGUS Image"
builders:
- docker
docker_name: sunet/argus-server
docker_tags:
- "v1.27.0_sunet-${GIT_COMMIT}"
docker_force_tag: true
docker_no_cache: true
docker_skip_tag_as_latest: false
docker_build_args: |
  BRANCH_NAME=v1.27.0
  REPO_URL=https://github.com/Uninett/Argus.git