version: '3.5'

services:
  argus-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BRANCH_NAME: "v1.25.0"
    ports:
      - "8000:8000"
    environment:
      - TIME_ZONE=Europe/Stockholm
      - DJANGO_SETTINGS_MODULE=dockersettings
      - DJANGO_SETTINGS_MODULE=argus.site.settings.dockerdev
      - PYTHONPATH=/var/opt/extrapython
      - STATIC_ROOT=/static
      - DATABASE_URL=postgresql://argus:HahF9araeKoo@postgres/argus
      - ARGUS_REDIS_SERVER=redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ${PWD}:/argus

  postgres:
    image: "postgres:14"
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=argus
      - POSTGRES_PASSWORD=HahF9araeKoo
      - POSTGRES_DB=argus

  redis:
    image: "redis:latest"
    restart: always

volumes:
  postgres:
    driver: local